### ISSUE TITLE
Duplicate UDP check needs to consider the ParentTable

### ISSUE THREAD

**Issue by ThomasRossmeisl** [coolOrangeLabs/bcpValidator#5]
The check for multiple UDP instances doesn't consider the parent table column and therefore causes false positives

E.g.

EntityID | ParentID | ParentTable | Name | cO_Value
-- | -- | -- | -- | --
3129393 | 2987 | Folder | Description | S02
10569 | 2987 | Iteration | Rev Number | -
10570 | 2987 | Iteration | Title | Flange 3" 09-53-551/59
10573 | 2987 | Iteration | Project Number | N/A
10574 | 2987 | Iteration | Unit | 00 - Not Relevant
10576 | 2987 | Iteration | Process cell | 00 - Not Relevant
10577 | 2987 | Iteration | Description | AISI 316L
8287967 | 2987 | Iteration | Approved By | null
8918028 | 2987 | Iteration | Author | EMA
9548089 | 2987 | Iteration | Part Number | ANH-005008027
10182347 | 2987 | Iteration | Group number | null

**Comment by marcomirandola** [comment]
fixed
