### ISSUE TITLE
Error when connecting to Vault

### ISSUE THREAD

**Issue by ThomasRossmeisl** [coolOrangeLabs/bcpValidator#7]
There are our result from BCP Checker. We not was able to finish BCP Checker because after log-in in to Vault we received DLL version problem.
  
![validator ssl](https://user-images.githubusercontent.com/34453713/45496767-7f9fc080-b776-11e8-8386-de8aea689938.png)

But in attachment you can find just half log of BCP Checker.

 Note that the Vault uses ssl

**Comment by gessner79** [comment]
VDF is used to connect to Vault, SSL shouldn't be an issue.
